---
  - name: Install certbot dependencies
    become: true
    apt:
      pkg: "{{item}}"
      state: present
    with_items:
      - augeas-lenses
      - ca-certificates
      - dialog
      - gcc
      - libaugeas0
      - libffi-dev
      - libpython-dev
      - libpython2.7-dev
      - libssl-dev
      - python
      - python-dev
      - python-setuptools
      - python-virtualenv
      - python2.7-dev

  - name: "Create certbot dir"
    become: true
    file:
      path: "{{certbot_dir}}"
      state: directory
      mode: 0755

  - name: Get certbot
    become: true
    get_url:
      url: "https://dl.eff.org/certbot-auto"
      dest: "{{certbot_dir}}/certbot-auto"
      mode: a+x

  - name: Run default
    when: le_ssl_certs is not defined
    become: true
    command: "{{certbot_dir}}/certbot-auto certonly --email {{letsencrypt_email}} --domains {{([server_name] + server_aliases) | join(',')}} --apache --agree-tos --expand --non-interactive"

  - name: Generate SSL Certificates
    when: le_ssl_certs is defined
    become: true
    with_items: "{{le_ssl_certs}}"
    command: "{{certbot_dir}}/certbot-auto certonly --email {{letsencrypt_email}} --domains {{item.domains | join(',')}} --cert-name {{item.cert_name}} --apache --agree-tos --expand --non-interactive"

  - name: Enable mod_rewrite
    become: true
    apache2_module:
      name: rewrite
      state: present

  - name: Enable mod_ssl
    become: true
    apache2_module:
      name: ssl
      state: present

  - name: "Re-run apache rails_project to get SSL configuration"
    include_role:
      name: apache-rails

  - name: Setup cron job to auto renew
    become: true
    cron:
      name: Auto-renew SSL
      job: "{{certbot_dir}}/certbot-auto renew --quiet --no-self-upgrade"
      hour: 0
      minute: 33
      state: present
