---
  - name: Install certbot dependencies
    apt:
      pkg: "{{item}}"
      state: present
    with_items:
      - augeas-lenses
      - ca-certificates
      - dialog
      - gcc
      - libaugeas0
      - libffi-dev
      - libpython-dev
      - libpython2.7-dev
      - libssl-dev
      - python
      - python-dev
      - python-setuptools
      - python-virtualenv
      - python2.7-dev

  - name: Create certbot directory
    file:
      path: "{{certbot_dir}}"
      state: directory
      mode: 0755
      owner: "{{deploy_user}}"

  - name: Get certbot
    get_url:
      url: "https://dl.eff.org/certbot-auto"
      dest: "{{certbot_dir}}/certbot-auto"
      mode: a+x
    sudo: true

  - name: Run certbot
    command: "{{certbot_dir}}/certbot-auto certonly --email {{letsencrypt_email}} --domains {{([server_name] + server_aliases) | join(',')}} --apache --agree-tos --non-interactive --expand"
    args:
      creates: /etc/letsencrypt/live/{{server_name}}/cert.pem
    sudo: true

  - name: Enable mod_rewrite
    apache2_module:
      name: rewrite
      state: present
    sudo: true

  - name: Enable mod_ssl
    apache2_module:
      name: ssl
      state: present
    sudo: true

  - name: Create SSL Apache config
    template:
      src: project-le-ssl.conf
      dest: /etc/apache2/sites-available/{{project_name}}-le-ssl.conf
    sudo: true
    notify: apache restart

  - name: Symlink {{project_name}}-le-ssl.conf to sites-enabled
    file:
      src: /etc/apache2/sites-available/{{project_name}}-le-ssl.conf
      dest: /etc/apache2/sites-enabled/{{project_name}}-le-ssl.conf
      state: link
    sudo: true
    notify: apache restart

  - name: Force redirect to https (1/3)
    lineinfile:
      dest: /etc/apache2/sites-available/{{project_name}}.conf
      line: "RewriteEngine on"
      state: present
      insertbefore: "</VirtualHost>"
    sudo: true
    notify: apache restart

  - name: Force redirect to https (2/3)
    lineinfile:
      dest: /etc/apache2/sites-available/{{project_name}}.conf
      line: "RewriteCond %{SERVER_NAME} ={{item}}\nRewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,NE,R=permanent]"
      state: present
      insertbefore: "</VirtualHost>"
    sudo: true
    with_items: "{{ ([server_name] + server_aliases) }}"
    notify: apache restart

  - name: Setup cron job to auto renew
    cron:
      name: Auto-renew SSL
      job: "{{certbot_dir}}/certbot-auto renew --no-self-upgrade"
      hour: 4
      state: present
