---
  server_aliases: []
  template_src_path: project.conf
  # TODO Replace with LetsEncrypt.
  #ssl_enabled: false
  #ssl_server_crt: ./files/{{project_name}}/server.crt
  #ssl_intermediate_crt: ./files/{{project_name}}/intermediate.crt
