---
galaxy_info:
  author: Manuel Tiago Pereira
  description: Installs Phusion Passenger.
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
  - name: Ubuntu
    versions:
    - lucid
    - precise
    - saucy
    - trusty
  categories:
    - web
dependencies: []

