- set_fact:
    puma_installed: true

- name: Create shared/config/puma
  file: path=/u/apps/{{project_name}}/shared/config/puma group=deploy owner=deploy state=directory
  tags: puma

- name: Add puma shared/config
  template: src=puma.rb dest=/u/apps/{{project_name}}/shared/config/puma/{{rails_env}}.rb group=deploy owner=deploy force=yes mode=755
  tags: puma

- name: Make shared/tmp/sockets
  file: path=/u/apps/{{project_name}}/shared/tmp/sockets group=deploy owner=deploy state=directory
  tags: tmp

- name: Install puma monit script
  template:
    src: puma-monit-rc
    dest: /etc/monit/conf-available/puma_{{project_name}}_{{rails_env}}

- name: Clean up old puma monit scripts
  shell: rm -f /etc/monit/conf.d/puma_*

- name: Enable puma monit script
  file:
    src: /etc/monit/conf-available/puma_{{project_name}}_{{rails_env}}
    dest: /etc/monit/conf-enabled/puma_{{project_name}}_{{rails_env}}
    state: link
  notify:
    - restart_monit

