- set_fact:
    puma_installed: true

- name: Create shared/config/puma
  file: path=/u/apps/{{project_name}}/shared/config/puma group=deploy owner=deploy state=directory
  tags: puma

- name: Add puma shared/config
  template: src=puma.rb dest=/u/apps/{{project_name}}/shared/config/puma/{{rails_env}}.rb force=yes mode=755
  tags: puma

- name: Make shared/tmp/sockets
  file: path=/u/apps/{{project_name}}/shared/tmp/sockets group=deploy owner=deploy state=directory
  tags: tmp

- name: Install puma monit script
  template:
    src: puma-monit-rc
    dest: /etc/monit/conf.d/puma_{{project_name}}_{{rails_env}}
  sudo: true
  notify: validate_monit

