---
- name: apache restart
  service: name=apache2 state=restarted
  become: true

- name: stop webserver
  service: name=apache2 state=stopped
  become: true

- name: start webserver
  service: name=apache2 state=started
  become: true
