---
  - name: Enable syslog communication to sensor
    lineinfile:
      dest: "/etc/rsyslog.d/50-default.conf"
      line: "*.* @{{alienvault_usm_anywhere_sensor_ip}}:514"
      state: present
    become: true
    when: ansible_distribution == 'Ubuntu'
    tags:
      - alienvault

  - name: Enable syslog communication to sensor
    lineinfile:
      dest: "/etc/rsyslog.conf"
      line: "*.* @{{alienvault_usm_anywhere_sensor_ip}}:514"
      state: present
    become: true
    when: ansible_distribution == 'Amazon'
    tags:
      - alienvault

  - name: Restart rsyslog
    service:
      name: rsyslog
      enabled: yes
      state: restarted
    become: true
    tags:
      - alienvault
