---
- name: Configure the PostgreSQL APT key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Configure the PostgreSQL APT repositories
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release}}-pgdg main"
                  state=present

- name: Install PostGIS
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}

- name: "Enable postgres postgis"
  become: true
  become_user: postgres
  postgresql_ext:
    db: "{{database_name}}"
    name: postgis
    state: present
