{{rails_env}}:
  adapter: {{database_adapter}}
  encoding: unicode
  pool: {{database_pool}}
  database: {{database_name}}
  username: {{database_user}}
  password: {{database_password}}
  host: {{database_host}}

{% if databaseyml_addendum is defined %}
{% for dict in databaseyml_addendum %}
{% for name, config in dict.items() %}
{{name}}:
 {% for key, value in config.items() %}
 {{key}}: {{value}}
 {% endfor %}
{% endfor %}
{% endfor %}
{% endif %}
