---
  - name: Install delayed_job monit script
    template:
      src: delayed-job-monit-rc
      dest: /etc/monit/conf.d/delayed_job_{{project_name}}_{{rails_env}}
    sudo: true
    notify: monit

  - name: Remove old upstart files
    file:
      path: /etc/init/delayed-job.conf
      state: absent
    sudo: true

  - name: Remove old monit files
    file:
      path: /etc/monit/conf.d/delayed_job
      state: absent
    sudo: true
