---
  - name: Create postgresql user
    postgresql_user:
      name: "{{database_user}}"
      password: "{{database_password}}"
      state: present
    become: true
    become_user: postgres

  - name: Create postgresql database
    postgresql_db:
      name: "{{database_name}}"
      owner: "{{database_user}}"
      template: template1
      state: present
    become: true
    become_user: postgres

  - name: Grant all privileges on database to user
    postgresql_privs:
      database: "{{database_name}}"
      privs: ALL
      roles: "{{database_user}}"
      state: present
      type: database
    become: true
    become_user: postgres

  - name: "Enable postgres hstore"
    become: true
    become_user: postgres
    postgresql_ext:
      db: "{{database_name}}"
      name: hstore
      state: present

  - include: backups.yml
    become: true
